package com.opencontacts.core.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalConfiguration
import java.util.Locale

@Composable
fun isArabicUi(): Boolean {
    val configuration = LocalConfiguration.current
    val locale = remember(configuration) {
        configuration.locales.takeIf { !it.isEmpty }?.get(0) ?: Locale.getDefault()
    }
    return locale.language.equals("ar", ignoreCase = true)
}

@Composable
fun localizedText(value: String): String {
    val isArabic = isArabicUi()
    return remember(value, isArabic) { localizeText(value, isArabic) }
}

fun localizeText(value: String, isArabic: Boolean): String {
    if (!isArabic) return value
    val trimmed = value.trim()
    phraseMap[trimmed]?.let { return it }

    dynamicPatterns.firstNotNullOfOrNull { it(trimmed) }?.let { return it }
    return value
}

private val dynamicPatterns: List<(String) -> String?> = listOf(
    { text ->
        Regex("^(\\d+) contact\\(s\\)$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "$it جهة اتصال" }
    },
    { text ->
        Regex("^(\\d+) selected$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "تم تحديد $it" }
    },
    { text ->
        Regex("^Default view for (.+)$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "العرض الافتراضي لـ $it" }
    },
    { text ->
        Regex("^Showing starred contacts only$").matchEntire(text)?.let { "يعرض المفضلة فقط" }
    },
    { text ->
        Regex("^Show only favorite contacts in this vault$").matchEntire(text)?.let { "اعرض المفضلة فقط داخل هذه الخزنة" }
    },
    { text ->
        Regex("^Deleted contacts will be kept for (.+) before permanent removal\\.$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "سيتم الاحتفاظ بجهات الاتصال المحذوفة لمدة $it قبل الحذف النهائي." }
    },
    { text ->
        Regex("^Hold delete for (\\d+) ms to clear the whole number\\.$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "اضغط مطولًا على الحذف لمدة $it مللي ثانية لمسح الرقم كاملًا." }
    },
    { text ->
        Regex("^Current vault$").matchEntire(text)?.let { "الخزنة الحالية" }
    },
    { text ->
        Regex("^Add contact to (.+)$").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "إضافة جهة اتصال إلى $it" }
    },
    { text ->
        Regex("""^Delete (.+)\? This removes its isolated data\. If it was the last or default vault, a safe fallback vault will be recreated automatically\.$""").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "حذف $it؟ سيؤدي ذلك إلى إزالة بياناتها المعزولة. وإذا كانت آخر خزنة أو الخزنة الافتراضية فسيتم إنشاء خزنة بديلة آمنة تلقائيًا." }
    },
    { text ->
        Regex("""^(.+) is selected\. Delete requires one more explicit confirmation\.$""").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "$it محددة الآن. الحذف يحتاج إلى تأكيد إضافي واضح." }
    },
    { text ->
        Regex("""^(\d+) selected contact\(s\) will be moved to trash\.$""").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "سيتم نقل $it جهة اتصال محددة إلى المحذوفات." }
    },
    { text ->
        Regex("""^(\d+) favorite contact\(s\) ready for quick calling\.$""").matchEntire(text)?.groupValues?.getOrNull(1)?.let { "$it جهة مفضلة جاهزة للاتصال السريع." }
    },
    { text ->
        Regex("^Switch vault$").matchEntire(text)?.let { "التبديل إلى هذه الخزنة" }
    },
    { text ->
        Regex("^Matched contact$").matchEntire(text)?.let { "جهة مطابقة" }
    },
    { text ->
        Regex("^Visual strip — swipe left and right to browse folders\\.$").matchEntire(text)?.let { "شريط بصري — اسحب يمينًا ويسارًا لاستعراض المجلدات." }
    },
    { text ->
        Regex("^Choose the active vault, then jump into all contacts, folders, or tags from the same panel\\.$").matchEntire(text)?.let { "اختر الخزنة النشطة ثم انتقل منها مباشرة إلى كل الجهات أو المجلدات أو الوسوم." }
    },
)

private val phraseMap = mapOf(
    "Back" to "رجوع",
    "Appearance" to "المظهر",
    "Theme mode" to "وضع المظهر",
    "Apply light, dark, or system theming instantly across the app." to "طبّق الوضع الفاتح أو الداكن أو وضع النظام فورًا في التطبيق كله.",
    "Mode" to "الوضع",
    "Changes apply live without restarting." to "يتم تطبيق التغيير مباشرة بدون إعادة تشغيل.",
    "Theme studio" to "استوديو المظهر",
    "Google Keep inspired palette and background customization with live preview." to "تخصيص الألوان والخلفيات مع معاينة مباشرة بشكل مريح وعملي.",
    "Theme preset" to "نمط الواجهة",
    "Accent palette" to "لوحة الألوان",
    "Background category" to "فئة الخلفية",
    "Corner style" to "شكل الزوايا",
    "Choose how rounded cards and surfaces should feel." to "اختر شكل الزوايا ومستوى الاستدارة في البطاقات والأسطح.",
    "Language" to "اللغة",
    "Arabic and English switch with real locale changes." to "التبديل بين العربية والإنجليزية مع تغيير فعلي للغة واتجاه الواجهة.",
    "App language" to "لغة التطبيق",
    "Uses translated strings and correct layout direction." to "يستخدم نصوصًا مترجمة واتجاه واجهة صحيح.",
    "Live preview" to "معاينة مباشرة",
    "Check cards, backgrounds, and accents before leaving the screen." to "عاين البطاقات والخلفيات والألوان قبل مغادرة الشاشة.",
    "Choose a preset" to "اختر نمطًا",
    "Choose an accent" to "اختر لونًا أساسيًا",
    "Choose a background" to "اختر خلفية",
    "Preferences" to "التفضيلات",
    "Appearance & list" to "المظهر والقائمة",
    "Default sort order" to "الترتيب الافتراضي",
    "Choose how contacts are ordered when no search query is active." to "اختر طريقة ترتيب جهات الاتصال عند عدم وجود بحث.",
    "List density" to "كثافة القائمة",
    "Compact fits more contacts on screen. Comfortable keeps larger spacing." to "المضغوط يعرض جهات أكثر، والمريح يترك مسافات أكبر.",
    "Show contact photos in list" to "إظهار صور جهات الاتصال في القائمة",
    "Hide photos for a cleaner and lighter scrolling experience." to "أخفِ الصور لتجربة تصفح أنظف وأخف.",
    "Show favorites first" to "إظهار المفضلة أولًا",
    "Keep favorite contacts near the top of the contacts tab." to "حافظ على جهات المفضلة قرب أعلى قائمة الجهات.",
    "Search & behavior" to "البحث والسلوك",
    "Default start tab" to "العلامة الافتراضية عند البدء",
    "Choose what opens first on the home screen." to "اختر ما الذي يفتح أولًا في الشاشة الرئيسية.",
    "Open contact directly on tap" to "فتح الجهة مباشرة عند الضغط",
    "When disabled, tapping during selection mode only adjusts selection." to "عند إيقافه، الضغط أثناء وضع التحديد يغيّر التحديد فقط.",
    "Show blocked contacts in search" to "إظهار الجهات المحظورة في البحث",
    "Hide blocked contacts from inline search results when disabled." to "عند إيقافه يتم إخفاء الجهات المحظورة من نتائج البحث السريع.",
    "Show recent calls preview" to "إظهار معاينة المكالمات الأخيرة",
    "Display recent call entries inside the contact details page." to "اعرض المكالمات الأخيرة داخل صفحة تفاصيل الجهة.",
    "Calling" to "الاتصال",
    "Call button behavior" to "سلوك زر الاتصال",
    "Choose whether the call button should place the call inside OpenContacts after taking the default phone role, or hand the number off to the phone app on the device." to "اختر هل زر الاتصال يُجري المكالمة من داخل OpenContacts بعد تعيينه كتطبيق الهاتف الافتراضي، أم يسلّم الرقم لتطبيق الهاتف في الجهاز.",
    "Default phone app status" to "حالة تطبيق الهاتف الافتراضي",
    "OpenContacts must become the default phone app if you want in-app calling, incoming call UI, and ongoing call controls through Telecom." to "يجب جعل OpenContacts تطبيق الهاتف الافتراضي إذا أردت الاتصال من داخل التطبيق وواجهة المكالمات الواردة والتحكم في المكالمات الجارية.",
    "Set OpenContacts as default phone app" to "اجعل OpenContacts تطبيق الهاتف الافتراضي",
    "Open Android's dialer-role prompt directly from inside the app for a faster setup path." to "افتح طلب دور تطبيق الهاتف مباشرة من داخل التطبيق لإعداد أسرع.",
    "Dial pad" to "لوحة الاتصال",
    "Show keypad letters" to "إظهار حروف الأزرار",
    "Display ABC/DEF style hints on keypad buttons." to "اعرض الحروف المساعدة مثل ABC وDEF على أزرار اللوحة.",
    "Auto-format numbers" to "تنسيق الأرقام تلقائيًا",
    "Add lightweight spacing while typing for easier reading." to "أضف مسافات خفيفة أثناء الكتابة لتسهيل القراءة.",
    "Show T9 suggestions" to "إظهار اقتراحات T9",
    "Suggest matching contacts while typing on the dial pad." to "اقترح جهات مطابقة أثناء الكتابة على لوحة الاتصال.",
    "Long-press backspace clears all" to "الضغط المطوّل على الحذف يمسح الكل",
    "Keep single tap for one digit and long press for full clear." to "تبقى الضغطة العادية لحذف رقم واحد والمطوّلة لمسح الرقم كاملًا.",
    "Dial pad toggle size" to "حجم زر لوحة الاتصال",
    "Make the show/hide button a little bigger and keep it comfortable." to "كبّر زر الإظهار والإخفاء قليلًا مع الحفاظ على راحته.",
    "Backspace hold duration" to "مدة الضغط المطوّل على الحذف",
    "Choose how long you need to hold delete before the whole number clears." to "اختر المدة المطلوبة للضغط على الحذف قبل مسح الرقم كاملًا.",
    "Haptic feedback" to "الاهتزاز التفاعلي",
    "Use subtle vibration for quick toggles and keypad interactions." to "استخدم اهتزازًا خفيفًا مع الأزرار والتفاعلات السريعة.",
    "Groups, folders & tags" to "المجموعات والمجلدات والوسوم",
    "Tag sorting" to "ترتيب الوسوم",
    "Choose how tags are ordered inside the workspace." to "اختر طريقة ترتيب الوسوم داخل مساحة العمل.",
    "Folder placement" to "مكان ظهور المجلدات",
    "Folder drawer layout" to "عرض المجلدات في القائمة الجانبية",
    "Choose whether folders appear in the side drawer or on the main screen as a visual carousel." to "اختر ما إذا كانت المجلدات تظهر في القائمة الجانبية أو في الشاشة الرئيسية كشريط صور أفقي.",
    "Show folders in the side drawer as the classic vertical list or as a horizontal visual strip with cover images." to "اعرض المجلدات في القائمة الجانبية كقائمة عمودية كلاسيكية أو كشريط أفقي بصري مع صور الغلاف.",
    "Hide empty folders and tags" to "إخفاء المجلدات والوسوم الفارغة",
    "Keep lists cleaner by hiding classifications with no contacts." to "حافظ على القوائم أنظف عبر إخفاء التصنيفات التي لا تحتوي جهات اتصال.",
    "Trash retention" to "الاحتفاظ بالمحذوفات",
    "Choose how long deleted contacts stay in the trash before permanent removal." to "اختر مدة بقاء جهات الاتصال المحذوفة في المحذوفات قبل الإزالة النهائية.",
    "Safety and export" to "الأمان والتصدير",
    "Confirm before delete" to "تأكيد قبل الحذف",
    "Ask before deleting a contact or multiple selected contacts." to "اطلب تأكيدًا قبل حذف جهة واحدة أو عدة جهات محددة.",
    "Confirm before block/unblock" to "تأكيد قبل الحظر أو إلغاء الحظر",
    "Require confirmation before changing blocked state." to "اطلب تأكيدًا قبل تغيير حالة الحظر.",
    "Include timestamp in exported filenames" to "إضافة التاريخ والوقت إلى أسماء ملفات التصدير",
    "Safer for repeated exports and easier to trace later." to "أكثر أمانًا مع التصدير المتكرر وأسهل في التتبع لاحقًا.",
    "Settings" to "الإعدادات",
    "Vaults" to "الخزائن",
    "Create, edit, delete, lock, and choose the default vault" to "أنشئ الخزائن وعدّلها واحذفها واقفلها واختر الخزنة الافتراضية",
    "Groups & Tags" to "المجلدات والوسوم",
    "Manage folders and tags for the current vault from one place" to "أدر المجلدات والوسوم الخاصة بالخزنة الحالية من مكان واحد",
    "Import & Export" to "الاستيراد والتصدير",
    "Import CSV or VCF, export in multiple formats, and open backup & restore tools" to "استورد CSV أو VCF وصدّر بصيغ متعددة وافتح أدوات النسخ الاحتياطي والاستعادة",
    "Sorting, search, density, trash retention, and contact behavior" to "الترتيب والبحث وكثافة العرض والاحتفاظ بالمحذوفات وسلوك جهات الاتصال",
    "Calling, notifications & roles" to "الاتصال والإشعارات والأدوار",
    "Default phone role, overlay access, ongoing call return, and recording" to "دور تطبيق الهاتف والوصول فوق التطبيقات والعودة للمكالمة الجارية والتسجيل",
    "Blocked Contacts" to "الجهات المحظورة",
    "Review blocked contacts and unblock directly" to "راجع الجهات المحظورة وألغِ حظرها مباشرة",
    "Trash" to "المحذوفات",
    "Restore deleted contacts or remove them permanently" to "استعد الجهات المحذوفة أو احذفها نهائيًا",
    "Theme presets, accent colors, language, and visual presentation" to "أنماط الواجهة والألوان واللغة والشكل العام",
    "About" to "حول التطبيق",
    "Version, privacy-first scope, and implementation notes" to "الإصدار ونطاق الخصوصية وملاحظات التنفيذ",
    "SYSTEM" to "النظام",
    "LIGHT" to "فاتح",
    "DARK" to "داكن",
    "ROUNDED" to "مستدير",
    "COMPACT" to "مضغوط",
    "SHARP" to "حاد",
    "CLASSIC" to "كلاسيكي",
    "GLASS" to "زجاجي",
    "SOFT" to "ناعم",
    "MINIMAL" to "بسيط",
    "ELEGANT" to "أنيق",
    "PASTEL" to "باستيل",
    "BLUE" to "أزرق",
    "EMERALD" to "زمردي",
    "SUNSET" to "غروب",
    "LAVENDER" to "لافندر",
    "ROSE" to "وردي",
    "AMBER" to "كهرماني",
    "SLATE" to "رمادي مزرق",
    "NATURE" to "طبيعة",
    "ABSTRACT" to "تجريدي",
    "EN" to "الإنجليزية",
    "AR" to "العربية",
    "FIRST_NAME" to "الاسم الأول",
    "LAST_NAME" to "الاسم الأخير",
    "RECENTLY_ADDED" to "الأحدث إضافة",
    "MOST_CONTACTED" to "الأكثر تواصلًا",
    "COMFORTABLE" to "مريح",
    "CONTACTS" to "جهات الاتصال",
    "CALL_LOG" to "الأخيرة",
    "OPENCONTACTS_DEFAULT_APP" to "الاتصال من داخل OpenContacts",
    "SYSTEM_PHONE_APP" to "التحويل لتطبيق الهاتف في الجهاز",
    "ALPHABETICAL" to "أبجدي",
    "MOST_USED" to "الأكثر استخدامًا",
    "LIST" to "قائمة",
    "CAROUSEL" to "شريط أفقي",
    "SIDE_DRAWER" to "القائمة الجانبية",
    "MAIN_SCREEN" to "الشاشة الرئيسية",
    "BOTH" to "كلاهما",
    "MANUAL" to "يدوي",
    "1 Week" to "أسبوع",
    "1 Month" to "شهر",
    "1 Year" to "سنة",
    "Lifetime" to "دائمًا",
    "Compact" to "صغير",
    "Large" to "كبير",
    "Extra large" to "كبير جدًا",
    "Fast" to "سريع",
    "Balanced" to "متوازن",
    "Slow" to "بطيء",
    "Idle" to "جاهز",
    "Typing" to "جارٍ الكتابة",
    "Paste" to "لصق",
    "Save" to "حفظ",
    "Enter number" to "أدخل الرقم",
    "Hide dial pad" to "إخفاء لوحة الاتصال",
    "Show dial pad" to "إظهار لوحة الاتصال",
    "Delete digit" to "حذف رقم",
    "Call" to "اتصال",
    "Add contact" to "إضافة جهة اتصال",
    "Show all" to "عرض الكل",
    "Assign folder" to "تعيين مجلد",
    "Assign tag" to "تعيين وسم",
    "Delete selected contacts?" to "حذف الجهات المحددة؟",
    "Delete" to "حذف",
    "Cancel" to "إلغاء",
    "Select all" to "تحديد الكل",
    "Remove from favorites" to "إزالة من المفضلة",
    "Add to favorites" to "إضافة إلى المفضلة",
    "Edit" to "تعديل",
    "Share" to "مشاركة",
    "QR" to "QR",
    "Favorites" to "المفضلة",
    "Add" to "إضافة",
    "Add favorites" to "إضافة إلى المفضلة",
    "All contacts are already in favorites." to "كل جهات الاتصال موجودة بالفعل في المفضلة.",
    "Current vault view" to "محتوى الخزنة الحالية",
    "All contacts" to "كل جهات الاتصال",
    "Folders" to "المجلدات",
    "Tags" to "الوسوم",
    "No folders yet in this vault." to "لا توجد مجلدات بعد في هذه الخزنة.",
    "No tags yet in this vault." to "لا توجد وسوم بعد في هذه الخزنة.",
    "Share contact(s)" to "مشاركة جهة الاتصال/الجهات المحددة",
    "Share as QR" to "مشاركة كرمز QR",
    "Scan to import contact data quickly." to "امسح الرمز لاستيراد بيانات جهة الاتصال بسرعة.",
    "Unable to share QR" to "تعذر مشاركة رمز QR",
    "QR saved to gallery" to "تم حفظ رمز QR في المعرض",
    "Unable to save QR" to "تعذر حفظ رمز QR",
    "Collapse" to "تصغير",
    "Expand" to "تكبير",
    "Close" to "إغلاق",
    "Contact details" to "تفاصيل جهة الاتصال",
    "More" to "المزيد",
    "Share as text" to "مشاركة كنص",
    "Share as file" to "مشاركة كملف",
    "Contact not found" to "جهة الاتصال غير موجودة",
    "The vault may be locked or the contact may no longer exist." to "قد تكون الخزنة مقفلة أو أن جهة الاتصال لم تعد موجودة.",
    "Add note" to "إضافة ملاحظة",
    "Encrypted note" to "ملاحظة مشفرة",
    "Remove folder from contact?" to "إزالة المجلد من جهة الاتصال؟",
    "The contact will stay intact. Only the selected folder link will be removed." to "ستبقى جهة الاتصال كما هي. سيتم فقط إزالة ربط المجلد المحدد.",
    "Remove tag?" to "إزالة الوسم؟",
    "This removes only the selected tag from this contact." to "سيؤدي هذا إلى إزالة الوسم المحدد فقط من جهة الاتصال.",
    "No primary phone" to "لا يوجد رقم أساسي",
    "Blocked" to "محظور",
    "Silent ring" to "رنين صامت",
    "QR Code" to "رمز QR",
    "Blocking" to "الحظر",
    "Folder" to "مجلد",
    "Create or assign folders directly from here." to "أنشئ المجلدات أو اربطها مباشرة من هنا.",
    "Tap Manage to attach one or more folders. Long-press a chip to remove it." to "اضغط إدارة لربط مجلد واحد أو أكثر. واضغط مطولًا على الشريحة لإزالته.",
    "Manage" to "إدارة",
    "No folder assigned yet" to "لم يتم تعيين مجلد بعد",
    "Add tags directly from the contact page." to "أضف الوسوم مباشرة من صفحة جهة الاتصال.",
    "Tap to browse only. Long-press a tag chip to remove it with confirmation." to "الضغط للتصفح فقط. اضغط مطولًا على شريحة الوسم لإزالته مع تأكيد.",
    "Add tag" to "إضافة وسم",
    "No tags assigned" to "لا توجد وسوم مضافة",
    "Call history" to "سجل المكالمات",
    "Show less" to "عرض أقل",
    "Show more" to "عرض المزيد",
    "Recent call preview is disabled" to "معاينة المكالمات الأخيرة متوقفة",
    "Enable it from Preferences to show recent calls inside contact details." to "فعّلها من التفضيلات لعرض المكالمات الأخيرة داخل تفاصيل جهة الاتصال.",
    "No call history found" to "لا يوجد سجل مكالمات",
    "This contact will show all matching device calls after number normalization." to "ستظهر لهذه الجهة كل مكالمات الجهاز المطابقة بعد توحيد صيغة الرقم.",
    "Unknown number" to "رقم غير معروف",
    "Notes" to "الملاحظات",
    "No notes yet" to "لا توجد ملاحظات بعد",
    "Capture protected follow-up notes and context for this contact." to "سجّل ملاحظات متابعة وسياقًا محميًا لهذه الجهة.",
    "Timeline" to "الخط الزمني",
    "No activity yet" to "لا يوجد نشاط بعد",
    "The timeline shows notes, edits, and blocked-state changes." to "يعرض الخط الزمني الملاحظات والتعديلات وتغييرات حالة الحظر.",
    "Contact links" to "روابط جهة الاتصال",
    "Facebook URL" to "رابط فيسبوك",
    "Instagram URL or handle" to "رابط أو اسم مستخدم إنستجرام",
    "Website / other link" to "موقع أو رابط آخر",
    "Blocking mode" to "وضع الحظر",
    "Allow calls normally" to "السماح بالمكالمات بشكل طبيعي",
    "Reject immediately before the full incoming UI interrupts you" to "رفض المكالمة فورًا قبل أن تقاطعك واجهة المكالمة الواردة الكاملة",
    "Keep the call active but mute sound and vibration for this contact" to "ابقِ المكالمة نشطة لكن اكتم الصوت والاهتزاز لهذه الجهة",
    "Allow" to "سماح",
    "Instant reject" to "رفض فوري",
    "Display name" to "الاسم الظاهر",
    "Primary phone" to "الرقم الأساسي",
    "Tags (comma separated)" to "الوسوم (مفصولة بفواصل)",
    "Contact photo" to "صورة جهة الاتصال",
    "No photo selected" to "لم يتم اختيار صورة",
    "Photo attached" to "تم إرفاق صورة",
    "Add photo" to "إضافة صورة",
    "Change photo" to "تغيير الصورة",
    "Add folder" to "إضافة مجلد",
    "Clear all" to "مسح الكل",
    "Tag name" to "اسم الوسم",
    "Contact QR Code" to "رمز QR لجهة الاتصال",
    "QR code" to "رمز QR",
    "Share, save, or expand this QR for quick import." to "شارك هذا الرمز أو احفظه أو كبّره للاستيراد السريع.",
    "Share contact" to "مشاركة جهة الاتصال",
    "Share contact file" to "مشاركة ملف جهة الاتصال",
    "Share InstaPay details" to "مشاركة تفاصيل InstaPay",
    "Share QR" to "مشاركة QR",
    "Share contact as text" to "مشاركة جهة الاتصال كنص",
    "Fonts" to "الخطوط",
    "Choose a calmer app-wide font, or bring your own TTF / OTF file from the phone." to "اختر خطًا أهدأ للتطبيق كله، أو أضف ملف خط TTF أو OTF من الهاتف.",
    "App font" to "خط التطبيق",
    "Custom font file" to "ملف الخط المخصص",
    "Imported fonts are copied into app storage and applied across the interface." to "يتم نسخ الخطوط المستوردة إلى تخزين التطبيق وتطبيقها على الواجهة بالكامل.",
    "None" to "لا يوجد",
    "Import custom font" to "استيراد خط مخصص",
    "Clear custom font" to "إزالة الخط المخصص",
    "SYSTEM_DEFAULT" to "خط النظام الافتراضي",
    "SERIF" to "Serif",
    "MONO" to "Monospace",
    "CURSIVE" to "Cursive",
    "ROUNDED_SYSTEM" to "مستدير من النظام",
    "CONDENSED" to "مكثف",
    "ARABIC_NASKH" to "نسخي عربي",
    "CUSTOM_UPLOAD" to "خط مرفوع من الهاتف",
    "Light mode" to "الوضع الفاتح",
    "Dark mode" to "الوضع الداكن",
    "Display name" to "الاسم الظاهر",
    "Primary phone" to "الرقم الأساسي",
    "Folder" to "المجلد",
    "Tags (comma separated)" to "الوسوم (تفصل بفاصلة)",
    "Contact photo" to "صورة جهة الاتصال",
    "No photo selected" to "لم يتم اختيار صورة",
    "Photo attached" to "تم إرفاق صورة",
    "Add photo" to "إضافة صورة",
    "Change photo" to "تغيير الصورة",
    "Remove" to "إزالة",
    "Add tag" to "إضافة وسم",
    "Tag name" to "اسم الوسم",
    "Contact QR Code" to "رمز QR لجهة الاتصال",
    "Share, save, or expand this QR for quick import." to "شارك هذا الرمز أو احفظه أو كبّره للاستيراد السريع.",
    "Collapse" to "تصغير",
    "Expand" to "تكبير",
    "Close" to "إغلاق",
    "Manage links" to "إدارة الروابط",
    "WhatsApp" to "واتساب",
    "Telegram" to "تيليجرام",
    "Facebook" to "فيسبوك",
    "Instagram" to "إنستجرام",
    "InstaPay" to "إنستاباي",
    "Recents" to "الأخيرة",
    "Vault manager" to "إدارة الخزائن",
    "New vault" to "خزنة جديدة",
    "Vault control center" to "مركز إدارة الخزائن",
    "Choose one default vault, open any vault without losing your place, and add contacts directly into any vault from here." to "اختر خزنة افتراضية واحدة، وافتح أي خزنة دون أن تفقد مكانك، وأضف جهات الاتصال مباشرة إلى أي خزنة من هنا.",
    "Default" to "افتراضي",
    "Active" to "نشطة",
    "Selected vault" to "الخزنة المحددة",
    "Delete vault" to "حذف الخزنة",
    "Locked vault • requires unlock when opened" to "خزنة مقفلة • تحتاج إلى فتح عند الدخول",
    "Ready vault • can be used immediately" to "خزنة جاهزة • يمكن استخدامها فورًا",
    "Unlocked" to "مفتوحة",
    "Lock" to "قفل",
    "Use now" to "استخدمها الآن",
    "Make default" to "اجعلها افتراضية",
    "Create vault" to "إنشاء خزنة",
    "Edit vault" to "تعديل الخزنة",
    "Vault name" to "اسم الخزنة",
    "Set as default" to "اجعلها افتراضية",
    "Use this vault automatically on app start." to "استخدم هذه الخزنة تلقائيًا عند بدء التطبيق.",
    "Open this vault right after saving." to "افتح هذه الخزنة مباشرة بعد الحفظ.",
    "Add contact to" to "إضافة جهة اتصال إلى",
    "Name" to "الاسم",
    "More phones" to "أرقام إضافية",
    "One phone per line" to "رقم واحد في كل سطر",
    "Favorite" to "مفضلة",

    "OpenContacts is the current default" to "OpenContacts هو التطبيق الافتراضي الحالي",
    "Another phone app is currently the default" to "يوجد تطبيق هاتف آخر هو الافتراضي حاليًا",
    "Already enabled" to "مفعل بالفعل",
    "Open prompt" to "فتح الطلب",
    "Share contact(s)" to "مشاركة جهة/جهات الاتصال",
    "Edit contact" to "تعديل جهة اتصال",

    "Fonts" to "الخطوط",
    "Choose a calmer app-wide font, or bring your own TTF / OTF file from the phone." to "اختر خطًا هادئًا للتطبيق كله أو أضف خط TTF / OTF من الهاتف.",
    "App font" to "خط التطبيق",
    "Custom font file" to "ملف الخط المخصص",
    "Imported fonts are copied into app storage and applied across the interface." to "يتم نسخ الخطوط المستوردة إلى مساحة التطبيق وتطبيقها على الواجهة كلها.",
    "Import custom font" to "استيراد خط مخصص",
    "Clear custom font" to "مسح الخط المخصص",
    "None" to "لا يوجد",
    "SYSTEM_DEFAULT" to "افتراضي النظام",
    "ROUNDED_SYSTEM" to "نظامي ناعم",
    "CONDENSED" to "مكثف",
    "SERIF" to "سيريف",
    "MONO" to "أحادي المسافة",
    "CURSIVE" to "مخطوط",
    "ARABIC_NASKH" to "نسخي عربي",
    "CUSTOM_UPLOAD" to "خط مرفوع من الهاتف",
    "Live preview" to "معاينة مباشرة",
    "Check cards, backgrounds, accents, and text feel before leaving the screen." to "عاين شكل البطاقات والخلفيات والألوان والخط قبل مغادرة الشاشة.",
    "Locked" to "مقفلة",
    "Share contact(s)" to "مشاركة جهة/جهات الاتصال",
    "Delete selected contacts will be moved to trash." to "سيتم نقل الجهات المحددة إلى المحذوفات.",
    "favorite contact(s) ready for quick calling." to "جهة مفضلة جاهزة للاتصال السريع.",
    "Add folder" to "إضافة مجلد",
    "Clear all" to "مسح الكل",
    "Blocking mode" to "وضع الحظر",
    "Apply" to "تطبيق",
    "QR code" to "رمز QR",
    "Unable to share QR" to "تعذر مشاركة رمز QR",
    "QR saved to gallery" to "تم حفظ رمز QR في المعرض",
    "Choose SIM" to "اختر الشريحة",
    "Choose the SIM to place this call." to "اختر الشريحة التي تريد إجراء الاتصال منها.",
    "Choose the SIM to run this USSD code." to "اختر الشريحة التي تريد تشغيل كود USSD منها.",
    "The system phone app will complete the action after you choose a SIM." to "سيكمل تطبيق الهاتف في الجهاز العملية بعد اختيار الشريحة.",
    "OpenContacts will place the action after you choose a SIM." to "سيُجري OpenContacts العملية بعد اختيار الشريحة.",
    "Tap to use this SIM now" to "اضغط لاستخدام هذه الشريحة الآن",
    "SIM choice behavior" to "سلوك اختيار الشريحة",
    "Pick a default SIM or ask every time before placing the call." to "اختر شريحة افتراضية أو اسأل في كل مرة قبل إجراء الاتصال.",
    "ASK_EVERY_TIME" to "اسأل في كل مرة",
    "DEFAULT_SIM" to "الشريحة الافتراضية",
    "Default SIM" to "الشريحة الافتراضية",
    "Choose which SIM should be used when the calling mode is set to the default SIM option." to "اختر الشريحة التي سيتم استخدامها عندما يكون وضع الاتصال مضبوطًا على الشريحة الافتراضية.",
    "SIM chooser transparency" to "شفافية نافذة اختيار الشريحة",
    "Controls how solid the centered SIM chooser card should look." to "يتحكم في مدى عتامة بطاقة اختيار الشريحة في منتصف الشاشة.",
    "SIM chooser size" to "حجم نافذة اختيار الشريحة",
    "Adjust how wide the centered SIM chooser card should be." to "اضبط عرض بطاقة اختيار الشريحة في منتصف الشاشة.",
    "Very light" to "خفيفة جدًا",
    "Soft" to "ناعمة",
    "Balanced" to "متوازنة",
    "Solid" to "صلبة",
    "Compact" to "مضغوطة",
    "Large" to "كبيرة",
    "USSD" to "USSD",
    "Unable to save QR" to "تعذر حفظ رمز QR",

)
